version: '3'

services:
    php:
        image: php:7.3-cli
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - "8080"
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        environment:
            - COMPOSER_ALLOW_SUPERUSER=1
        command: >
            sh -c "composer install -d /app &&
            cp /app/docker.global.php /app/config/autoload &&
            /app/vendor/bin/zend-expressive-swoole start"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
        container_name: elasticsearch_662
        environment:
          - http.host=0.0.0.0
          - transport.host=0.0.0.0
          - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        volumes:
          - esdata:/usr/share/elasticsearch/data
          - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        ports:
          - 9200:9200
          - 9300:9300
        ulimits:
          memlock:
            soft: -1
            hard: -1
          nofile:
            soft: 65536
            hard: 65536

    kibana:
        image: docker.elastic.co/kibana/kibana:6.6.2
        container_name: kibana_662
        environment:
          - SERVER_HOST=0.0.0.0
        volumes:
          - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
          - 5601:5601

volumes:
  esdata:
    driver: local
